CREATE TRIGGER PEOPLE_COUNT
	AFTER INSERT ON plan_user FOR EACH ROW
	BEGIN
		UPDATE plan SET PEOPLE_NUMBER=PEOPLE_NUMBER+1
		WHERE ID=NEW.PLAN_ID;
	END;

CREATE TRIGGER PEOPLE_DROP
	AFTER DELETE ON plan_user FOR EACH ROW
	BEGIN
		UPDATE plan SET PEOPLE_NUMBER=PEOPLE_NUMBER-1
		WHERE ID=OLD.PLAN_ID;
	END;